### ISSUE TITLE
Rename the project to netcdf

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/netcdfjs#13]
Also change the name on npm and republish it

**Comment by maasencioh** [comment]
there are people using this project and all the project implementing the parser are using this standard, as you can see in [this list of projects](https://github.com/Unidata/netcdf-c#latest-releases)

**Comment by lpatiny** [comment]
Actually netcdf is taken on npm so we can do nothing ... Too bad because of course netcdf appears on the top of the list looking for this keyword on npm.

I have the impression that if you put a '-' in the name npm will split it and use it as keyword. So in the future if the name we want is taken, like netcdf, it would make sense probably to use 'netcdf-js' in order to be indexed correctly.

**Comment by maasencioh** [comment]
in any case, that keyword is in the package.json and therefore it changes nothing
