### ISSUE TITLE
Cannot read multiple variables that share the same record dimension (UNLIMITED) 

### ISSUE THREAD

**Issue by PBrockmann** [cheminfo-js/netcdfjs#17]
I am working with the last 0.7 release and I have noticed that I cannot read multiple variables that share the same record dimension (UNLIMITED). Only one is listed.

The test netcdf file header is:
<pre>
netcdf monthly_navy_winds_01 {
dimensions:
	FNOCX = 144 ;
	FNOCY = 73 ;
	TIME = UNLIMITED ; // (132 currently)
variables:
	double FNOCX(FNOCX) ;
	double FNOCY(FNOCY) ;
	double TIME(TIME) ;
	float UWND(TIME, FNOCY, FNOCX) ;
	float VWND(TIME, FNOCY, FNOCX) ;
</pre>

When I read this file with the following code, I cannot read the last VWND variable. Only 4 variables are listed.

<pre>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://www.lactame.com/lib/netcdfjs/0.7.0/netcdfjs.js"></script>

<script>
$( document ).ready(function() {
//######################################################################################################

var urlpath =  "monthly_navy_winds_01.nc"
var reader;

var oReq = new XMLHttpRequest();
oReq.open("GET", urlpath, true);
oReq.responseType = "blob";

oReq.onload = function(oEvent) {
  var blob = oReq.response;
  reader_url = new FileReader();
  
  reader_url.onload = function(e) {
    reader = new netcdfjs(this.result);

    console.log(reader.variables);
  }
      
  reader_url.readAsArrayBuffer(blob);
};
oReq.send(); //start process

//######################################################################################################
});
</script>
</pre>

Now if I change the unlimited dimension to a fixed one with
<pre>
ncks --fix_rec_dmn TIME monthly_navy_winds_01.nc -o monthly_navy_winds_02.nc
</pre>

Then you get as a netcdf header:

<pre>
netcdf monthly_navy_winds_02 {
dimensions:
	FNOCX = 144 ;
	FNOCY = 73 ;
	TIME = 132
variables:
	double FNOCX(FNOCX) ;
	double FNOCY(FNOCY) ;
	double TIME(TIME) ;
	float UWND(TIME, FNOCY, FNOCX) ;
	float VWND(TIME, FNOCY, FNOCX) ;
</pre>

And then you get all the variables listed !

The file is a classic one you can download from the NOAA-PMEL ferret/pyferret codes.
https://github.com/NOAA-PMEL/FerretDatasets/blob/master/data/monthly_navy_winds.cdf

**Comment by targos** [comment]
@maasencioh would you like to take a look?

**Comment by PBrockmann** [comment]
I cannot reproduce the error today. Very strange.
