### ISSUE TITLE
If i can load netcdf data without nodejs

### ISSUE THREAD

**Issue by WangXiaoLun** [cheminfo-js/netcdfjs#7]
My project wants to load netcdf data only by front end and without nodejs,cound that be realize?

**Comment by maasencioh** [comment]
Hello @WangXiaoLun , yes you can, you have several options for parsing a javascript code, for example you could use [Browserify](http://browserify.org/)(this is an [example](https://wzrd.in/standalone/netcdfjs@latest) of how you could get it) or even you could use [our parsed](https://www.lactame.com/lib/netcdfjs/0.3.0/netcdfjs.min.js) version of it (it's pretty much the same)

**Comment by WangXiaoLun** [comment]
Thanks @maasencioh . O(∩_∩)O  And There is one more question. Can I set dataVariable?

**Comment by maasencioh** [comment]
sorry, we're currently only able to read data, not write it

**Comment by WangXiaoLun** [comment]
@maasencioh And cound I change NetCDFReader instance To ArrayBuffer again?

**Comment by WangXiaoLun** [comment]
If i want to modify code to support above requirements,Do you have any advice for me? O(∩_∩)O

**Comment by maasencioh** [comment]
@WangXiaoLun currently the library is not designed for doing this, but if you have to do it you should consider to read this:
  * [NetCDF grammar](https://www.unidata.ucar.edu/software/netcdf/docs/file_format_specifications.html)
  * [Writing files best practices](https://www.unidata.ucar.edu/software/netcdf/docs/BestPractices.html)

I also have to update the major of the reading library, but I'm currently working on other projects, so I don't know when I'll finish this
